version: "3.9"

services:
  backend:
    build: ./Voixmate/backend
    container_name: voixmate-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=your_secret_key_here
      - FIREBASE_KEY_PATH=/run/secrets/firebase_key
    volumes:
      - ./Voixmate/backend:/app
    secrets:
      - firebase_key

secrets:
  firebase_key:
    file: ./Voixmate/backend/serviceAccountKey.json
